'use client'

import "./globals.css";
import { Inter } from "next/font/google";
import AuthContext from "./AuthContext";
import Navbar from "./components/Navbar";
import React from "react";
import TopBar from "./components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = React.useState(false);

  return (
    <AuthContext>
      <head></head>

      <html lang="en">
        <body className="">
          <TopBar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
          <div className="flex h-[calc(100vh-40px)]">
            <Navbar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
            {children}
          </div>
        </body>
      </html>
    </AuthContext>
  );
}
